SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
	FROM EMP;

SELECT DEPTNO, DNAME, LOC
	FROM DEPT;

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, DNAME, LOC
	FROM EMP JOIN DEPT
	USING(DEPTNO);
	
