CREATE TABLE SIMPLEBOARD(
	SEQ NUMBER,
	WRITER VARCHAR2(50),
	TITLE VARCHAR2(100),
	CONTENT VARCHAR2(200),
	REGDATE DATE DEFAULT SYSDATE,
	DELFALG CHAR(1) DEFAULT 'N',
	CONSTRAINT SIMPLEBOARD_PK PRIMARY KEY(SEQ)
);

CREATE SEQUENCE SIMPLEBOARD_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO SIMPLEBOARD(SEQ, WRITER, TITLE, CONTENT, REGDATE, DELFALG)
	VALUES(SIMPLEBOARD_SEQ.NEXTVAL, '네모', '네모글', '네모네모합니다.', SYSDATE, 'N');
INSERT INTO SIMPLEBOARD(SEQ, WRITER, TITLE, CONTENT, REGDATE, DELFALG)
	VALUES(SIMPLEBOARD_SEQ.NEXTVAL, '세모', '세모', '세모세모합니다.', SYSDATE, 'N');
INSERT INTO SIMPLEBOARD(SEQ, WRITER, TITLE, CONTENT, REGDATE, DELFALG)
	VALUES(SIMPLEBOARD_SEQ.NEXTVAL, '동그라미', '동글', '동글동글합니다.', SYSDATE, 'N');
	
-- 전체 게시글 조회
SELECT SEQ, WRITER, TITLE, CONTENT, REGDATE, DELFALG 
	FROM SIMPLEBOARD s 
	WHERE DELFALG = 'N'
	ORDER BY REGDATE DESC;
	
-- 게시글 1개 조회
SELECT SEQ, WRITER, TITLE, CONTENT, REGDATE, DELFALG 
	FROM SIMPLEBOARD s 
	WHERE SEQ=1;
	
-- 새글 작성
INSERT INTO SIMPLEBOARD(SEQ, WRITER, TITLE, CONTENT)
	VALUES(SIMPLEBOARD_SEQ.NEXTVAL, '뾰족이', '뾰족뾰족', '아파요ㅠㅠ');
	
-- 수정
UPDATE SIMPLEBOARD SET TITLE='네모세모', CONTENT='네모세모합니다.'
	WHERE SEQ=1;
	
-- 삭제
UPDATE SIMPLEBOARD SET DELFALG=UPPER('y')
	WHERE SEQ=1;