CREATE TABLE ANSWERBOARD(
	SEQ NUMBER,
	ID VARCHAR2(30) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(1000), 
	REF NUMBER NOT NULL,
	STEP NUMBER NOT NULL,
	DEPTH NUMBER NOT NULL,
	REGDATE DATE DEFAULT SYSDATE NOT NULL,
	DELFLAG CHAR(1) DEFAULT 'N'
);

CREATE SEQUENCE ANSWERBOARD_SEQ START WITH 1 INCREMENT BY 1;
ALTER TABLE ANSWERBOARD ADD CONSTRAINT ANSWERBOARD_PK PRIMARY KEY (SEQ);

CREATE TABLE USERINFO(
ID VARCHAR2(30) NOT NULL,
NAME VARCHAR2(100) NOT NULL,
PASSWORD VARCHAR2(100) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
AUTH CHAR(1) NOT NULL,
DELFLAG CHAR(1) NOT NULL,
JOINDATE DATE NOT NULL
);

ALTER TABLE USERINFO ADD CONSTRAINT EMAIL_UK UNIQUE (EMAIL);
ALTER TABLE USERINFO ADD CONSTRAINT USERINFO_PK PRIMARY KEY (ID);


-- 1) ROOT 글 입력
-- 2-1) 답글 입력 : 선택된 ROOT글의 하위에 있는 답글들의 STEP을 +1씩 증가 시킴
-- 2-2) 답글 입력 : ROOT 글에 소속된 답글을 입력
SELECT SEQ, ID, TITLE, "REF", STEP, "DEPTH", REGDATE, DELFLAG
	FROM ANSWERBOARD
	ORDER BY REF DESC, STEP ASC;

SELECT "REF", STEP+1
	FROM ANSWERBOARD a 
	WHERE "REF"=(SELECT REF
					FROM ANSWERBOARD a2 
					WHERE SEQ='2')
		AND STEP>(SELECT STEP
					FROM ANSWERBOARD a3
					WHERE SEQ='2')
	
INSERT INTO ANSWERBOARD(SEQ, ID, TITLE, CONTENT, "REF", STEP, "DEPTH", REGDATE, DELFLAG)
	VALUES(ANSWERBOARD_SEQ.NEXTVAL, 'A001', 'root글 첫 번째', '임정운 바보', '1', '0', '0', '2020-10-16', 'N');

INSERT INTO ANSWERBOARD(SEQ, ID, TITLE, CONTENT, "REF", STEP, "DEPTH", REGDATE, DELFLAG)
	VALUES(ANSWERBOARD_SEQ.NEXTVAL, 'A001', 'root글 두 번째', '돼지갈비 땡긴다', '2', '0', '0', '2020-10-05', 'N');
	
INSERT INTO ANSWERBOARD(SEQ, ID, TITLE, CONTENT, "REF", STEP, "DEPTH", REGDATE, DELFLAG)
	VALUES(ANSWERBOARD_SEQ.NEXTVAL, 'A001', 'root글 세 번째', '임정운 바보', '3', '0', '0', '2020-10-04', 'N');
	
INSERT INTO ANSWERBOARD(SEQ, ID, TITLE, CONTENT, "REF", STEP, "DEPTH", REGDATE, DELFLAG)
	VALUES(ANSWERBOARD_SEQ.NEXTVAL, 'A002', '답글 1', '초밥도 땡긴다', '2', '1', '1', '2020-10-04', 'N');
	
INSERT INTO ANSWERBOARD(SEQ, ID, TITLE, CONTENT, "REF", STEP, "DEPTH", REGDATE, DELFLAG)
	VALUES(ANSWERBOARD_SEQ.NEXTVAL, 'A002', '답글 2', '업진살...', '2', '2', '1', '2020-10-04', 'N');
	
INSERT INTO ANSWERBOARD(SEQ, ID, TITLE, CONTENT, "REF", STEP, "DEPTH", REGDATE, DELFLAG)
	VALUES(ANSWERBOARD_SEQ.NEXTVAL, 'A003', '답글 1-1', '치키인', '3', '2', '2', '2020-10-04', 'N');