-- file board
CREATE TABLE BOARD(
	B_SEQ NUMBER PRIMARY KEY, 
	TITLE VARCHAR2(500), 
	WRITER VARCHAR2(20), 
	CONTENT VARCHAR2(2000), 
	REGDATE DATE DEFAULT SYSDATE, 
	DELFLAG CHAR(1) DEFAULT 'N'
);

CREATE SEQUENCE BOARD_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE REPLY(
	R_SEQ NUMBER PRIMARY KEY,
	B_SEQ NUMBER, 
	WRITER VARCHAR2(20), 
	CONTENT VARCHAR2(2000), 
	REGDATE DATE DEFAULT SYSDATE, 
	DELFLAG CHAR(1) DEFAULT 'N'
);

CREATE SEQUENCE REPLY_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE FILEFILE(
	F_SEQ NUMBER PRIMARY KEY,
	B_SEQ NUMBER NOT NULL,
	WRITER VARCHAR2(200),
	ORIGIN_FNAME VARCHAR2(1000) NOT NULL,
	STORED_FNAME VARCHAR2(1000) NOT NULL,
	FILE_SIZE NUMBER NOT NULL,
	F_REGDATE DATE DEFAULT SYSDATE NOT NULL,
	F_DELFLAG CHAR(1) DEFAULT 'N' NOT NULL
);

CREATE SEQUENCE FILEFILE_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO HR.BOARD(B_SEQ, TITLE, WRITER, CONTENT)
		VALUES(BOARD_SEQ.NEXTVAL, '', '', '');
	
INSERT INTO HR.REPLY(R_SEQ, B_SEQ, WRITER, CONTENT)
		VALUES(REPLY_SEQ.NEXTVAL, 0, '', '');

INSERT INTO HR.FILEFILE(F_SEQ, B_SEQ, WRITER, ORIGIN_FNAME, STORED_FNAME, FILE_SIZE, F_REGDATE, F_DELFLAG)
		VALUES(0, 0, '', '', '', 0, '', '');

SELECT B_SEQ, TITLE, WRITER, CONTENT, REGDATE , DELFLAG 
	FROM BOARD b ;
	
SELECT R_SEQ, B_SEQ, WRITER , CONTENT , REGDATE , DELFLAG 
	FROM REPLY r ;
	
SELECT F_SEQ, B_SEQ , WRITER , ORIGIN_FNAME , STORED_FNAME , FILE_SIZE , F_REGDATE , F_DELFLAG 
	FROM FILEFILE f ;

SELECT F_SEQ, ORIGIN_FNAME 
	FROM FILEFILE f 
	WHERE B_SEQ='';