-- 전체조회
SELECT EMPNO, ENAME , JOB , TO_CHAR(HIREDATE, 'YYYY-MM-DD') HIREDATE
	FROM EMP e ;

-- 상세조회
SELECT ENAME, JOB,  TO_CHAR(HIREDATE, 'YYYY-MM-DD') HIREDATE, SAL , NVL(COMM, 0) COMM 
	FROM EMP e
	WHERE EMPNO ='7369';