-- 일정 관리 게시판
CREATE TABLE CALRENDARBOARD(
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(30) NOT NULL,
	TITLE VARCHAR2(500) NOT NULL,
	CONTENT VARCHAR2(4000),
	MDATE VARCHAR2(12) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO HR.CALRENDARBOARD
(SEQ, ID, TITLE, CONTENT, MDATE, REGDATE)
VALUES((SELECT NVL(MAX(SEQ),0)+1 FROM CALRENDARBOARD c ), 'RABIT', '일정관리 게시판', '마지막 SERVLET 실습이다 야호', '202307241200', SYSDATE);
INSERT INTO HR.CALRENDARBOARD
(SEQ, ID, TITLE, CONTENT, MDATE, REGDATE)
VALUES((SELECT NVL(MAX(SEQ),0)+1 FROM CALRENDARBOARD c ), 'RABIT', '프로젝트 모임', '프로젝트 주제를 정하는 모임 잘 정리해야함', '202307251200', SYSDATE);
INSERT INTO HR.CALRENDARBOARD
(SEQ, ID, TITLE, CONTENT, MDATE, REGDATE)
VALUES((SELECT NVL(MAX(SEQ),0)+1 FROM CALRENDARBOARD c ), 'RABIT', '즐거운 수업', '새로운 과목을 배운다', '202307251200', SYSDATE);
INSERT INTO HR.CALRENDARBOARD
(SEQ, ID, TITLE, CONTENT, MDATE, REGDATE)
VALUES((SELECT NVL(MAX(SEQ),0)+1 FROM CALRENDARBOARD c ), 'RABIT', '프로젝트 회의', '각 주제별 프로젝트 구성의 최종 단계 회의', '202307251200', SYSDATE);
INSERT INTO HR.CALRENDARBOARD
(SEQ, ID, TITLE, CONTENT, MDATE, REGDATE)
VALUES((SELECT NVL(MAX(SEQ),0)+1 FROM CALRENDARBOARD c ), 'RABIT', 'UI/UX 회의', 'AJAX로 작업하자 : AJAX란?', '202307251200', SYSDATE);
INSERT INTO HR.CALRENDARBOARD`
(SEQ, ID, TITLE, CONTENT, MDATE, REGDATE)
VALUES((SELECT NVL(MAX(SEQ),0)+1 FROM CALRENDARBOARD c ), 'RABIT', 'API 모듈 발표', '발표를 해야 하는데...', '202307281200', SYSDATE);

SELECT SEQ, ID, TITLE, MDATE, REGDATE
	FROM(
		SELECT ROW_NUMBER() OVER(PARTITION BY SUBSTR(MDATE, 1, 8) ORDER BY MDATE) RN,
			SEQ, ID, TITLE, MDATE, REGDATE 
			FROM CALRENDARBOARD c2 
			WHERE ID='RABIT' AND SUBSTR(MDATE,1,6)='202307'
	)
	WHERE RN BETWEEN 1 AND 3;
		
INSERT INTO CALRENDARBOARD
(SEQ, ID, TITLE, CONTENT, MDATE, REGDATE)
VALUES((SELECT NVL(MAX(SEQ),0)+1 FROM CALRENDARBOARD c ), 'RABIT', '일정관리 게시판', '마지막 SERVLET 실습이다 야호', '202307241200', SYSDATE);

SELECT SEQ, ID, TITLE, MDATE, REGDATE
	FROM CALRENDARBOARD c 
	WHERE ID='RABIT'
		AND SUBSTR(MDATE,1,8) = '20230725';

SELECT COUNT(*)
	FROM CALRENDARBOARD c
	WHERE ID='RABIT'
		AND SUBSTR(MDATE,1,8) = '20230725';
	
SELECT SEQ, ID, TITLE, CONTENT, MDATE, REGDATE
	FROM CALRENDARBOARD c 
	WHERE SEQ=1
		AND ID='RABIT'
		AND SUBSTR(MDATE,1,8) = '20230725';
		
DELETE FROM CALRENDARBOARD c 
	WHERE SEQ=1;
	
SELECT b.B_SEQ AS B_SEQ, TITLE , b.B_WRITER AS B_WRITER  , B_CONTENT , B_REGDATE , B_DELFLAG , R_SEQ , R_WRITER , R_CONTENT , R_REGDATE , R_DELFLAG , F_SEQ , ORIGIN_FNAME 
			FROM BOARD b LEFT JOIN (SELECT R_SEQ , B_SEQ, R_WRITER , R_CONTENT , R_REGDATE , R_DELFLAG, RN
										FROM (SELECT R_SEQ , B_SEQ, R_WRITER , R_CONTENT , R_REGDATE , R_DELFLAG ,
												ROW_NUMBER() OVER(ORDER BY R_SEQ ASC) RN
												FROM REPLY
												WHERE B_SEQ=2)) r
			ON b.B_SEQ = r.B_SEQ
			LEFT JOIN FILEFILE f 
			ON b.B_SEQ = f.B_SEQ 
			WHERE f.B_SEQ = 2
				AND RN BETWEEN 1 AND 10
			ORDER BY F_SEQ ASC, R_SEQ ASC;
		
		
		
		
SELECT COUNT(*)
	FROM REPLY r 
	WHERE B_SEQ=2;