CREATE TABLE INFO(
	SEQ NUMBER PRIMARY KEY,
	NAME VARCHAR2(10) NOT NULL,
	PHONE VARCHAR2(11) NOT NULL,
	AUTH CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL	
);

CREATE SEQUENCE INFO_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO INFO(SEQ, NAME, PHONE, AUTH, REGDATE)
	VALUES(INFO_SEQ.NEXTVAL, '시계', '00711', 'U', SYSDATE);
	
SELECT SEQ, NAME, PHONE, AUTH, REGDATE
	FROM INFO i 
	WHERE SEQ = 1;
	
SELECT *
	FROM INFO i ;